Fix #783 Don't show button if --quickjump not present
haskell/haddock pull request #1108
Opened 2019-11-10 10:42 UTC by mpilgrem

In the TypeScript `init.ts`, makes `quickJump.init()` (which creates the button) conditional on the presence of meta tag `hasQuickJump` with content `"true"`.

In the Haskell, threads the `withQuickJump` flag result through to `headHtml` to create the meta tag, accordingly.

2019-11-10 14:26 UTC, mpilgrem commented
The CI build fails because of the existing commit e6ca100973c496cd98da3385594fa9a81320f7cb. Without that commit, it builds under Windows 10 using `stack`.

2019-11-13 09:32 UTC, mpilgrem commented
I have thought of a different approach to this, which I think is better, and will provide a revised pull request. The creation of the dummy `li` element is moved from the TypeScript to the Haskell and identified, and its existence (or not) replaces the use of the meta tag.

2021-01-15 04:55 UTC, Kleidukos requested changes
@mpilgrem Hi, and thank you very much for this PR! I left you a couple of comments and it should be good.
That being said, would you be able to include a screenshot of the updated interface when `--quickjump` isn't passed as an argument?

2021-01-15 04:55 UTC, Kleidukos commented on haddock-api/src/Haddock/Backends/Xhtml.hs
> +-- The TrueScript should replace this <li> element, given its id. However, in
I think you meant `TypeScript`?

2021-01-15 04:55 UTC, Kleidukos commented on haddock-api/src/Haddock/Backends/Xhtml.hs
> +
Extraneous blank line

2021-01-15 21:03 UTC, mpilgrem commented
Below is a screenshot of the updated interface when `--quickjump` is not passed as a command line option:

![image](https://user-images.githubusercontent.com/14206448/104778245-f7ca8680-5774-11eb-858d-e39dab5aaa95.png)

2021-01-15 21:05 UTC, mpilgrem commented
@Kleidukos, I have updated the PR to reflect your two comments and posted a screenshot.

2021-01-15 21:09 UTC, Kleidukos commented
@mpilgrem Brilliant! We are currently in a merge phase to backport PRs to the ghc-9.0 branch, so while I won't be merging your PR as it is now (since it's targeting the now-defunct ghc-8.8 branch), it will be ported to the next main branch.

Thanks again :sparkles:

2022-06-06 10:07 UTC, Kleidukos commented
@mergifyio rebase

2022-06-06 10:08 UTC, Kleidukos commented
@mergifyio rebase

2022-06-13 11:39 UTC, mpilgrem commented
@Kleidukos I saw your request for a rebase and the bot's failed attempt. I have rebased manually against the `ghc-9.2` branch and tested the rebased code locally by: (1) building `haddock.exe` locally with `stack` and `nightly-2022-06-12` (GHC 9.2.3); and (2) creating Haddock documentation for a simple test project (`stack new test`) with `haddock -o docs -h app/Main.hs src/Lib.hs` and `haddock -o docs -h --quickjump app/Main.hs src/Lib.hs` and reviewing the results using the `Live Server` extension for Visual Studio Code.

I experienced some initial difficulties with rebuilding the minified JS files in `haddock-api\resources\html`. I found I had to `npm install gulp@4.0.2` (previously it was local version 3.9.1) to get the `gulp` command to work without errors.

2022-06-13 11:48 UTC, Kleidukos commented
One more reason to reshape our frontend stacK

2022-06-13 11:49 UTC, Kleidukos approved these changes

2022-06-13 11:49 UTC, merged

2022-08-16 10:38 UTC, mpickering commented
This PR breaks the quickjump feature on `hackage.haskell.org`.

See https://gitlab.haskell.org/ghc/ghc/-/issues/21984

We will need to revert it for the 9.4.2 release.

2022-08-16 12:25 UTC, mpilgrem commented
@mpickering, sorry! I only ever tested locally. Is there a recommended way to test that pull requests for `haddock` will not break the Haddock functionality on Hackage?

2022-08-17 08:16 UTC, mpickering commented
I tested the changes by using a local hackage server (which is quite easy to setup, it's documented in the README).

I also noticed that quick jump was not supported for candidates, so I added that (https://github.com/haskell/hackage-server/pull/1122) so perhaps another way to test in future is upload a candidate for one of your packages to check everything is in order.