Hlint redundancies.
haskell/haddock pull request #1511
Opened 2022-07-24 13:25 UTC by philderbeast

See #1474 for redundant id, redundant return, redundant if, redundant <$>, redundant map and redundant lambda.

2023-01-10 16:34 UTC, Kleidukos commented
@mergifyIO rebase

2023-01-15 13:20 UTC, philderbeast commented
@Kleidukos I rebased, got HLint running again (it was barfing on InterfaceFile, https://github.com/ndmitchell/hlint/issues/1442) and followed hints about rendundancies except for redundant brackets. They're numerous and I'll do those on a separate pull request.

2023-01-23 17:35 UTC, Kleidukos submitted a review, later dismissed

2023-01-23 17:35 UTC, Kleidukos commented on haddock-test/src/Test/Haddock/Config.hs
> +        else pure ((flagsDiffTool flags) <|>) <*> defaultDiffTool
I'm not sure this brings any value, the original line is clearer

2023-01-23 17:36 UTC, Kleidukos requested changes
See comments. :) We're nearly there!

2024-05-18 12:28 UTC, philderbeast commented
Thanks for the review @Kleidukos. Closing here. I may create a new merge request for it over in the GHC repo.

2024-05-18 12:28 UTC, closed without merging